/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableauDeBordRouteImport } from './routes/tableau-de-bord'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as EngagementRouteImport } from './routes/engagement'
import { Route as ArbreDeLaPaixRouteImport } from './routes/arbre-de-la-paix'
import { Route as AlummaGindaRouteImport } from './routes/alumma-ginda'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'

const TableauDeBordRoute = TableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementRoute = EngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbreDeLaPaixRoute = ArbreDeLaPaixRouteImport.update({
  id: '/arbre-de-la-paix',
  path: '/arbre-de-la-paix',
  getParentRoute: () => rootRouteImport,
} as any)
const AlummaGindaRoute = AlummaGindaRouteImport.update({
  id: '/alumma-ginda',
  path: '/alumma-ginda',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/alumma-ginda': typeof AlummaGindaRoute
  '/arbre-de-la-paix': typeof ArbreDeLaPaixRoute
  '/engagement': typeof EngagementRoute
  '/projets': typeof ProjetsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/alumma-ginda': typeof AlummaGindaRoute
  '/arbre-de-la-paix': typeof ArbreDeLaPaixRoute
  '/engagement': typeof EngagementRoute
  '/projets': typeof ProjetsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/alumma-ginda': typeof AlummaGindaRoute
  '/arbre-de-la-paix': typeof ArbreDeLaPaixRoute
  '/engagement': typeof EngagementRoute
  '/projets': typeof ProjetsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/alumma-ginda'
    | '/arbre-de-la-paix'
    | '/engagement'
    | '/projets'
    | '/sitemap.xml'
    | '/tableau-de-bord'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/alumma-ginda'
    | '/arbre-de-la-paix'
    | '/engagement'
    | '/projets'
    | '/sitemap.xml'
    | '/tableau-de-bord'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/alumma-ginda'
    | '/arbre-de-la-paix'
    | '/engagement'
    | '/projets'
    | '/sitemap.xml'
    | '/tableau-de-bord'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AlummaGindaRoute: typeof AlummaGindaRoute
  ArbreDeLaPaixRoute: typeof ArbreDeLaPaixRoute
  EngagementRoute: typeof EngagementRoute
  ProjetsRoute: typeof ProjetsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TableauDeBordRoute: typeof TableauDeBordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tableau-de-bord': {
      id: '/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof TableauDeBordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement': {
      id: '/engagement'
      path: '/engagement'
      fullPath: '/engagement'
      preLoaderRoute: typeof EngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbre-de-la-paix': {
      id: '/arbre-de-la-paix'
      path: '/arbre-de-la-paix'
      fullPath: '/arbre-de-la-paix'
      preLoaderRoute: typeof ArbreDeLaPaixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumma-ginda': {
      id: '/alumma-ginda'
      path: '/alumma-ginda'
      fullPath: '/alumma-ginda'
      preLoaderRoute: typeof AlummaGindaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AlummaGindaRoute: AlummaGindaRoute,
  ArbreDeLaPaixRoute: ArbreDeLaPaixRoute,
  EngagementRoute: EngagementRoute,
  ProjetsRoute: ProjetsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TableauDeBordRoute: TableauDeBordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
